chore(release): 1.0.0 [skip ci]
# 1.0.0 (2022-12-28)

### Bug Fixes

* `defaultExclude` unused ([2015c2a](https://github.com/mikjori/revanced-cli/commit/2015c2a1dcc0290af237e2eb1ab4aaf5fc84d382))
* `Main-Class` attribute pointing to wrong method ([6e82418](https://github.com/mikjori/revanced-cli/commit/6e824189586bfa4f8aaac4a5f33aed8d59261115))
* `ZipAligner` not correctly calculating the file offset ([2975a47](https://github.com/mikjori/revanced-cli/commit/2975a47d0f682a92da7b3ed455f5078298b0cbaa))
* add back in: option to specify keystore file path ([c94471f](https://github.com/mikjori/revanced-cli/commit/c94471f4643e44b2b472ff0d826db0d2743bdc86))
* add callback for addFiles ([87ffaa4](https://github.com/mikjori/revanced-cli/commit/87ffaa4bdb25cb85c6ba7195f5d3b13b09a5f912))
* add execute permission to `./gradlew` file ([#36](https://github.com/mikjori/revanced-cli/issues/36)) ([072d9e1](https://github.com/mikjori/revanced-cli/commit/072d9e15d7e44b1080923f3afeb194eeb4fe4682))
* align every file ([96ec6a0](https://github.com/mikjori/revanced-cli/commit/96ec6a0384e4c710c36b99ccf88bb14c5addc7af))
* breaking changes by `revanced-patcher` dependency ([51d2504](https://github.com/mikjori/revanced-cli/commit/51d250491f390695aedc64e7ee71a9dcf99d695c))
* broken control flow of `includeFilter` ([a0644c7](https://github.com/mikjori/revanced-cli/commit/a0644c7045344e6a6c324392cb8f507a6d9dbfad))
* broken deprecation message ([e3e74ac](https://github.com/mikjori/revanced-cli/commit/e3e74ac0e9a844f9d717a499bca09e575dd90435))
* broken script `CONTENT_UNMOUNT_SCRIPT` ([be53e64](https://github.com/mikjori/revanced-cli/commit/be53e649a7a43de70ba2a7227c49b085001066a6))
* check for root even though when not needed ([0d7581a](https://github.com/mikjori/revanced-cli/commit/0d7581ad750525e59bd6c019d987c640588ead62))
* check if `packageVersion` is compatible with any from `compatiblePackages` ([32589c8](https://github.com/mikjori/revanced-cli/commit/32589c88e438e0a1375c256e9bb8a93f5a4d319b))
* ClassLoader not working with Java 9+ ([3a11e11](https://github.com/mikjori/revanced-cli/commit/3a11e1135bd1e8958dd21247622d549440725ead))
* CLI not working ([29105ba](https://github.com/mikjori/revanced-cli/commit/29105bab3dabd9d16af6b511caef9727f98afd1a))
* delete `outputFile` after deploying ([329f8a3](https://github.com/mikjori/revanced-cli/commit/329f8a383fe52f4c2a66075d893c6599d3550bee))
* deploy to `adb` ([f9b987e](https://github.com/mikjori/revanced-cli/commit/f9b987e858292332a4b99e4e4280647425b8c0b8))
* don't log when package is incompatible and `exclusive` option is used ([ad81a1b](https://github.com/mikjori/revanced-cli/commit/ad81a1b656586226f8b7b8d1123c52b0f3f2e6f7))
* don't print same patch multiple times ([f4b0469](https://github.com/mikjori/revanced-cli/commit/f4b04698d8c1717824e86f91da5e01c5021612da))
* dummy publish task (1/2) [skip ci] ([afff4c8](https://github.com/mikjori/revanced-cli/commit/afff4c8418bd33959440a3ac9e6c46816b3153ad))
* escape quotation mark in string ([6e21d81](https://github.com/mikjori/revanced-cli/commit/6e21d81964e8160e06ffda7051dd484e4aaaa432))
* exclude patcher dependency from minimizing ([d5794b9](https://github.com/mikjori/revanced-cli/commit/d5794b94ca19c9287190a3b863c97a089893cc07))
* fix noSuchMethodError ([00fec25](https://github.com/mikjori/revanced-cli/commit/00fec2508a3421b7b5a246254e0cb08850eab6ea))
* **gitignore:** ignore `options.toml` ([#158](https://github.com/mikjori/revanced-cli/issues/158)) ([7be9af0](https://github.com/mikjori/revanced-cli/commit/7be9af0942de2a834b9e57403d46263b65f1a422))
* gradle build script ([6ffba3e](https://github.com/mikjori/revanced-cli/commit/6ffba3ef0a089c01fd31b667a37a27e77186bbbd))
* gradle sync dependencies ([407efdc](https://github.com/mikjori/revanced-cli/commit/407efdc8df1bd15710a9617462bfb123cfe739fe))
* improper use of mount variable ([31853fe](https://github.com/mikjori/revanced-cli/commit/31853fe5393af04805857b78a54434e1c51e4c8e))
* invalid code flow when adding patches ([206f202](https://github.com/mikjori/revanced-cli/commit/206f2029d7498b6474c16a47cbe451c170fdd31f))
* invalid header when writing a `ZipFile` ([#169](https://github.com/mikjori/revanced-cli/issues/169)) ([6e703eb](https://github.com/mikjori/revanced-cli/commit/6e703eb8e8d7da0e52266c4965f37bc8aafb409c))
* keystore file not found exception ([#57](https://github.com/mikjori/revanced-cli/issues/57)) ([5b8537e](https://github.com/mikjori/revanced-cli/commit/5b8537e6b7922f1b44058c3a4fc2f56cb4e15e89))
* leftover TODOs ([5b1139c](https://github.com/mikjori/revanced-cli/commit/5b1139ce43df1f5c2c848a8209a9e618857031ce))
* Log not showing in CLI  ([#80](https://github.com/mikjori/revanced-cli/issues/80)) ([d9c5a17](https://github.com/mikjori/revanced-cli/commit/d9c5a179c529c386f66df4fa63cd321d396836b5)), closes [#79](https://github.com/mikjori/revanced-cli/issues/79)
* Make clear what the --exclusive command actually does ([a26b0ea](https://github.com/mikjori/revanced-cli/commit/a26b0ea64dcd0757b5b49c09137959751874d955))
* make cli compatible with breaking changes of the patcher ([555b38f](https://github.com/mikjori/revanced-cli/commit/555b38f386363661a1433d82b9825dc345855f65))
* make integrations optional ([bea8b82](https://github.com/mikjori/revanced-cli/commit/bea8b829c701eee3c5b0bd6fe41c2f3f7df48d9b))
* migrate from `PatchLoader.load(...)` to `JarPatchBundle(...).loadPatches()` ([cabd32f](https://github.com/mikjori/revanced-cli/commit/cabd32fda41d32616a61ae450c60e1ee7c35bc59))
* migrate to changes of patcher ([b30c737](https://github.com/mikjori/revanced-cli/commit/b30c7375a7ea61184be5dca19062ee74d1f97692))
* migrate to latest patcher api changes ([ace70e4](https://github.com/mikjori/revanced-cli/commit/ace70e417fdf280c7630a5a89a773879fd240e96))
* missing implementation ([48102c6](https://github.com/mikjori/revanced-cli/commit/48102c66077c4ae17e3de1076e9da72de5f00366))
* mount bind revanced.apk from magisk's mirror ([372470c](https://github.com/mikjori/revanced-cli/commit/372470c77b82e8601ca523e87a2cfd44f79d0e31))
* move the keystore to the output directory ([6ceb449](https://github.com/mikjori/revanced-cli/commit/6ceb449cf8539a92d89eeba8136fdc686319e2ef))
* null exception when resource patching is disabled ([#85](https://github.com/mikjori/revanced-cli/issues/85)) ([125fa06](https://github.com/mikjori/revanced-cli/commit/125fa06ca6bac66f790e4aba66887464189b3a63))
* only accept directories when looking for files in resource patch ([c76da7e](https://github.com/mikjori/revanced-cli/commit/c76da7e5ffa208860eea008dad358e4e3bb3d735))
* only upload `-all.jar` asset ([ca8e1ba](https://github.com/mikjori/revanced-cli/commit/ca8e1ba6af00e275c6981476f773b13b103799d1))
* overwrite output file ([2bfbbc2](https://github.com/mikjori/revanced-cli/commit/2bfbbc2eb9057e66a362d37973a108baf44edf7a))
* releases (2/2) ([227d8d9](https://github.com/mikjori/revanced-cli/commit/227d8d94c89ec24051bd5bc20808049164d92492))
* remove `-e` from `experimental` option ([3829136](https://github.com/mikjori/revanced-cli/commit/3829136c49ddce1dc6b01eda04ce013540b213c2))
* remove `excludePatches` check ([eb83cab](https://github.com/mikjori/revanced-cli/commit/eb83cabfff6fbc28dd892f15b8e28278e284caa9))
* remove logger from Signer.kt ([51e091c](https://github.com/mikjori/revanced-cli/commit/51e091ce4021418508044029aa5af6aa7d5162a3))
* remove requirement for solution [skip ci] ([#108](https://github.com/mikjori/revanced-cli/issues/108)) ([0ce680a](https://github.com/mikjori/revanced-cli/commit/0ce680a6f1de139434edd80876a168ff695c2d79))
* resolve signatures before applying patches ([c9941fe](https://github.com/mikjori/revanced-cli/commit/c9941fe182e11066c34c3d390352862bb0f95ca2))
* resource patcher ([9da4f70](https://github.com/mikjori/revanced-cli/commit/9da4f707ac62d11993021871ef39f4f1709ba89d))
* show actual version in CLI ([1dcdbc9](https://github.com/mikjori/revanced-cli/commit/1dcdbc9fe9e3ad2fe232ad3baa76d186817532a4))
* sign the aligned file instead of the input file ([22d2535](https://github.com/mikjori/revanced-cli/commit/22d2535af8b3ea8fa58b6beb2938d240afa0a17d))
* start with uppercase in log message ([ae91b0d](https://github.com/mikjori/revanced-cli/commit/ae91b0d597b107a152e1b630b8c16a795a7ca3b3))
* this tiny thing has caused me the worst headache ever in my life ([a37304e](https://github.com/mikjori/revanced-cli/commit/a37304e032c9bb7d8b76f48c7eeaededb8a32a1e))
* uncomment merging integrations ([f2d9da4](https://github.com/mikjori/revanced-cli/commit/f2d9da4dca890241f6fc52bc2049b5655bc2b8ae))
* unfinished todo message ([fb068ef](https://github.com/mikjori/revanced-cli/commit/fb068ef7532fc236086205b41756c26f53489645))
* unmount script `CONTENT_UMOUNT_SCRIPT` ([3a2fa30](https://github.com/mikjori/revanced-cli/commit/3a2fa30676338518ab4a320e16c4c1fab78e0615))
* update cli for new patcher version ([9fc2f96](https://github.com/mikjori/revanced-cli/commit/9fc2f9602aa2f134106fa400daf388176957dd57))
* update patcher to 1.2.5 ([055c282](https://github.com/mikjori/revanced-cli/commit/055c282dd3d147e3600bdfdf4fd6b4bd72cbf379))
* update patcher version ([499ce0a](https://github.com/mikjori/revanced-cli/commit/499ce0a6fb1993ad48ffdd9c9e8307e8d0c179c6))
* update patcher version ([0df936e](https://github.com/mikjori/revanced-cli/commit/0df936e99b01358a88a628af63eebb5ac92cae76))
* update patcher version ([80c11fe](https://github.com/mikjori/revanced-cli/commit/80c11fef734bdba9026e91f95ee0a4a522cbefab))
* update patcher version ([09b9027](https://github.com/mikjori/revanced-cli/commit/09b9027e5e28f0483e74b711cf65a7876267a339)), closes [#45](https://github.com/mikjori/revanced-cli/issues/45)
* update patcher version (fix apktool) ([496f821](https://github.com/mikjori/revanced-cli/commit/496f82121879443609667a792cc1e16441ef5c2f))
* use absolute file path for key store ([d335846](https://github.com/mikjori/revanced-cli/commit/d335846202b991e130882e9ce0ab268deb2e27ab))
* use correct prefix in log message ([1a67cd8](https://github.com/mikjori/revanced-cli/commit/1a67cd81da5ed7f259b6dbaeb66a7eef4a113034))
* use latest version of patches dependency ([029f1ad](https://github.com/mikjori/revanced-cli/commit/029f1ad72223e5be6664c2c8810ac35e5807d9a8))
* wrong keystore output path ([20fa179](https://github.com/mikjori/revanced-cli/commit/20fa17957e3e454b9755bc7b9b473b6c578cc593))
* wrong label in additional items [skip ci] ([cd3ded1](https://github.com/mikjori/revanced-cli/commit/cd3ded1fbdb0c8eb7485912d5cbd6a2dd7455658))
* wrong separator when using `ZipFileSystemUtils` ([20e15de](https://github.com/mikjori/revanced-cli/commit/20e15defc2b90aa5e79bad41c097bd0db8d5e12a))
* wrong use of dependency to `revanced-patches` ([351de6c](https://github.com/mikjori/revanced-cli/commit/351de6cb90aa0f2ec93e8b8f6c10d7d312082079))
* wrong use of variable substitution / typo ([81d53b5](https://github.com/mikjori/revanced-cli/commit/81d53b5518454e479b7a8f2e9be934bee30702af)), closes [revanced/revanced-cli#12](https://github.com/revanced/revanced-cli/issues/12)
* wrong variable inverted ([f694542](https://github.com/mikjori/revanced-cli/commit/f694542d64ccb06bfa4d042f26b6b7192d1e912e))

### Code Refactoring

* migrate from `Signature` to `Fingerprint` ([88852a4](https://github.com/mikjori/revanced-cli/commit/88852a45ac90ad9419c18f0cb3395745e62eadbf))

### Features

* `--custom-aapt2-binary` option ([#104](https://github.com/mikjori/revanced-cli/issues/104)) ([d8dbffd](https://github.com/mikjori/revanced-cli/commit/d8dbffd7a7ebc583476d368d2ae78853cbb40382))
* `--exclusive` switch ([#78](https://github.com/mikjori/revanced-cli/issues/78)) ([8e91c12](https://github.com/mikjori/revanced-cli/commit/8e91c12c5e3864c369005ef9fe7d9db668e86701))
* `--include` option ([#76](https://github.com/mikjori/revanced-cli/issues/76)) ([57a1e7c](https://github.com/mikjori/revanced-cli/commit/57a1e7c27fb0c4292e08332b88ccd57d69fa02c6))
* `--uninstall` switch ([#84](https://github.com/mikjori/revanced-cli/issues/84)) ([131100e](https://github.com/mikjori/revanced-cli/commit/131100ef0043924a9c11eb9886b4f6b0373690d9))
* `frameworkFolderLocation` patcher option ([bc17298](https://github.com/mikjori/revanced-cli/commit/bc17298a807ce035b8baa1f7c30e1392ca4ee43b))
* Add CLI ([6664f49](https://github.com/mikjori/revanced-cli/commit/6664f49a11d655fe0723ad4846673b39b08fcadd))
* add logging back ([4a23cb6](https://github.com/mikjori/revanced-cli/commit/4a23cb69bc385158d47b6ea8d3da54b0566a242c))
* add option to specify keystore file path ([9331594](https://github.com/mikjori/revanced-cli/commit/9331594706404df871d170110da753cde5058d02))
* add path for `cacheDirectory` and enable resource patching by default ([54c0a03](https://github.com/mikjori/revanced-cli/commit/54c0a03d44c8d1b586bc487ee1ca71859d6f0b57))
* Add progress bar ([8d96ec8](https://github.com/mikjori/revanced-cli/commit/8d96ec83cb11ac9323ef268884912961a2405435))
* add semantic-release ([78d7aa3](https://github.com/mikjori/revanced-cli/commit/78d7aa361e4079b979fbf31d4fca2a7eec445618))
* Added root-only adb runner (tested on emulator) ([37ecc5e](https://github.com/mikjori/revanced-cli/commit/37ecc5eaa6f9b6640061400270d192959e3d69b2))
* allow listing patches without other parameters ([#42](https://github.com/mikjori/revanced-cli/issues/42)) ([b977d70](https://github.com/mikjori/revanced-cli/commit/b977d7039f877be242823a4eef0fb8df6550dd05))
* better output for excluded patches ([#77](https://github.com/mikjori/revanced-cli/issues/77)) ([ac7c7a9](https://github.com/mikjori/revanced-cli/commit/ac7c7a9a1a5c08322e3b206780d4f31104d8b570))
* chcon on mount ([e1c7d10](https://github.com/mikjori/revanced-cli/commit/e1c7d1082a6946d1082c8744a1d0118c1a2263ea))
* check, if input file exists ([b6dff6d](https://github.com/mikjori/revanced-cli/commit/b6dff6d832de4a513a6d86b0a59b2458eddd23c2))
* debugging option ([1b645c6](https://github.com/mikjori/revanced-cli/commit/1b645c67db58eb4d49b5290fd247507c9b43a9c6))
* do not warn on incompatible packages ([39e377b](https://github.com/mikjori/revanced-cli/commit/39e377bc485e2892422e9712d30e6ff665856ac1))
* handle unmounting deleted files ([#148](https://github.com/mikjori/revanced-cli/issues/148)) ([3a733e5](https://github.com/mikjori/revanced-cli/commit/3a733e513717799ca0e32327e5b8be043680c556))
* improve logging ([df85fa3](https://github.com/mikjori/revanced-cli/commit/df85fa37ef067681a027e6fe9212c8a065d4981b))
* improve missing compatibility annotation tracing log ([2c7eb72](https://github.com/mikjori/revanced-cli/commit/2c7eb7274c713dfbcb53c5f3b6a9205c751914fa))
* integrations merge ([919b34e](https://github.com/mikjori/revanced-cli/commit/919b34e174e95ee9b6adef50e405b9bbe117803a))
* issue templates [skip ci] ([bac8c67](https://github.com/mikjori/revanced-cli/commit/bac8c67d6f7bc10a38bb98a2f6e3f5cf6fa2e3e1))
* load patches dynamically & use kotlinx.cli ([4624384](https://github.com/mikjori/revanced-cli/commit/4624384f28378efeb5cae54365169905a0ed4de7))
* migrate logger to `slf4j` ([6c4c192](https://github.com/mikjori/revanced-cli/commit/6c4c1924ee9ae75af3449749a6a82b7ae5572129))
* more efficient zipalign ([a942a57](https://github.com/mikjori/revanced-cli/commit/a942a57364777d6ab6fcb11e6171cc4b496c8540))
* Patch Options CLI implementation ([#132](https://github.com/mikjori/revanced-cli/issues/132)) ([3f5345a](https://github.com/mikjori/revanced-cli/commit/3f5345af6e45bfb6c91d52fc089ab18d81fdc998))
* remove extra zipalign step ([#106](https://github.com/mikjori/revanced-cli/issues/106)) ([c8e793e](https://github.com/mikjori/revanced-cli/commit/c8e793efab8eed39b2cb564bee80ef6e0b2a7d03))
* remove unused option `-r` ([467d838](https://github.com/mikjori/revanced-cli/commit/467d8387e646c88d24a30406a5b2e84065ef4d54))
* rename `debugging` option to `experimental` ([98bd6f3](https://github.com/mikjori/revanced-cli/commit/98bd6f3f4b3eb34c445cbd5e3a3196f399f8bb3b))
* run `release.yml` workflow on branch `dev` ([9a64730](https://github.com/mikjori/revanced-cli/commit/9a6473056b940c6df4860dd09c09d7ac61545f7d))
* section `acknowledgements` for issue templates ([0e3ecc3](https://github.com/mikjori/revanced-cli/commit/0e3ecc3a51540b71072ae0be0eb94d115a5b1f92))
* separate logger to stdout & stderr ([#63](https://github.com/mikjori/revanced-cli/issues/63)) ([0ddc2b5](https://github.com/mikjori/revanced-cli/commit/0ddc2b54b739dae3e8ccc983bab73fc84e72be0a))
* separate options for `--list` ([#60](https://github.com/mikjori/revanced-cli/issues/60)) ([52b3161](https://github.com/mikjori/revanced-cli/commit/52b316150de397ebdee979caf51d4cb20961cf70))
* show description when listing patches ([af32572](https://github.com/mikjori/revanced-cli/commit/af32572f29d0f0a45ee5c3e01ba4cf1f91fe2f10))
* simplify log message ([74d73ca](https://github.com/mikjori/revanced-cli/commit/74d73ca3a7ba2f5da872fe9a241629e1c143cd4e))
* support for `--install` ([d1ceab4](https://github.com/mikjori/revanced-cli/commit/d1ceab45c89901f79d46c62f03186502021afb26))
* trace logs when compatibility annotation is missing ([#166](https://github.com/mikjori/revanced-cli/issues/166)) ([c590bf5](https://github.com/mikjori/revanced-cli/commit/c590bf559c4d2d2667c2af0c0da23d4706fcd4b7))
* unmount all occurrences in `/proc/mounts` ([#131](https://github.com/mikjori/revanced-cli/issues/131)) ([4f4e1f9](https://github.com/mikjori/revanced-cli/commit/4f4e1f9834bf28d9be2efd4fd7bae19951b85258))
* use `am` instead of `monkey` to launch the app ([#159](https://github.com/mikjori/revanced-cli/issues/159)) ([6a35cf7](https://github.com/mikjori/revanced-cli/commit/6a35cf7ea46a4474120626ce03d28490cc96bf07))
* use `install` mode by default ([1a3db77](https://github.com/mikjori/revanced-cli/commit/1a3db77c21b5795220fbac1ec36827fc521fface))

### Reverts

* feat: remove extra zipalign step ([c3d8fec](https://github.com/mikjori/revanced-cli/commit/c3d8fecad0ed9d583b9f1f79bc271e0535d87be2))

### BREAKING CHANGES

* Not backwards compatible, since a lot of classes where renamed.